### ISSUE TITLE
Prepare for version 5.0

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-js#2721]
NodeJS 10 LTS will be end of life on 2020-04-30. We will release a major version because of this.

This issue is meant to track the work that we want to do for 5.0, regardless of dropping NodeJS 10 support as well as the things we can do specifically because we're dropping support for NodeJS 10.

Proposal for breaking changes:

- [x] #2872 Make `coverageAnalysis` default to `"perTest"` when command runner is not "command".
- [x] Implement the `ignorePatterns` proposal #1593
- [x] Allign report API #2766
- [x] Remove support for "create-react-app-ts" projectType in jest-runner #2787 
- [x] #2811
- [ ] See https://github.com/stryker-mutator/stryker-js/milestone/11
